#name which will dispaly in ACTION tab
name: My First Workflow
on: push  # when to trigger this actio.we can add multiple trigger eg: [push, merge]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My first job"
        - name: List file
          run: ls
        - name: Read File
          run: cat README.md