name: Storybook PR Workflow

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  storybook-preview:
    if: contains(github.event.pull_request.labels.*.name, 'storybook')
    runs-on: ubuntu-latest
    
    steps:

      - name: Deploy to Azure Static Web App (Preview)
        run: |
          # Add your Azure deployment commands for the preview environment
          echo "Deploying Storybook to Azure static web app preview environment"

      - name: Save PR Information
        run: echo ${{ toJson(github.event.pull_request) }} > pr_info.json

      - name: Upload PR Information
        uses: actions/upload-artifact@v4
        with:
          name: pr-info
          path: pr_info.json

